AppBundle\Entity\Restaurant:
    properties:
        lon:
            - NotBlank: ~
            - Range:
                min: -180
                max: 180
#            - Type:
#                type: 'float'
        lat:
            - NotBlank: ~
            - Range:
                min: -90
                max: 90
#            - Type:
#                type: 'float'
        name:
            - NotBlank: ~
        city:
            - NotBlank: ~
        street:
            - NotBlank: ~
        postalCode:
            - Regex:
                pattern: "/^[0-9]{2}-[0-9]{3}$/"
            - NotBlank: ~
        buildingNumber:
            - NotBlank: ~
        apartmentNumber:
        country:
            - NotBlank: ~

