fos_rest:
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'jsonp'], fallback_format: json, prefer_extension: false }
    view:
        mime_types:
            jsonp: ['application/javascript+jsonp']
            json: ['application/json']
        formats:
            rss: true
            xml: false
            json: true
            jsonp: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig